### ISSUE TITLE
Yeoman Q1 2014 Roadmap

### ISSUE THREAD

**Issue by addyosmani** [yeoman/yeoman#1264]
Based on our team discussions in 2014, this is how our roadmap for this quarter is shaping up :cake: 
## P0
- [x] Implement V1 of generator composability
- [ ] Implement V1 of packaged installer
- [x] Refresh user documentation for yeoman.io
- [x] Ship a sexy new design for yeoman.io
- [ ] Refresh generator API documentation (including inheritance, use jsDoc)
- [ ] Aim for ~100% PageSpeed score for our generated output
- [x] Ship a new codelab for getting started with Yeoman
- [x] Define roadmaps for Angular
- [ ] Define roadmaps for Ember
- [ ] Define roadmaps for Backbone
- [x] Define roadmaps for Polymer
- [ ] Define roadmaps for Chrome app
- [ ] Define roadmaps for the other generators.
## P1
- [ ] Improve project-wide unit testing
- [x] Author list of features official generators should update
- [x] Author doc on how to keep your generator updated
- [x] Implement a proof-of-concept webapp generator using Gulp
- [x] Implement proof-of-concept ES6 support -webapp, -ember
## P2
- [ ] Modularize the generator system
- [ ] Move parts of the generator system [into yo](https://github.com/yeoman/yo/issues/56)
- [ ] Implement code-style linking in our repos via JSCS
- [ ] Explore using esformatter for code-style enforcement
- [ ] Cross-project issue tracker cleanup

Comments/additions for consideration welcome :) Once we've nailed down the final list and priorities, I'll link to appropriate issues and we can start assigning issues to folks.
