### ISSUE TITLE
Issue and pull request templates for all repos 🙀

### ISSUE THREAD

**Issue by mischah** [yeoman/yeoman#1652]
Hej, 

after triaging just a few issues today I wish people would leave at least info about their OS, Node version and npm version.

I’m not sure, but I hope that explicitly asking for that in an issue template could help to prevent asking the same questions again and again.

So what do you thing about providing an issue and a PR template?

To reduce clutter in the project root we should store the Github »meta data« in a subdirectory as described [here](https://github.com/blog/2111-issue-and-pull-request-templates):
```
.github
├── CONTRIBUTING.md
├── ISSUE_TEMPLATE.md
└── PULL_REQUEST_TEMPLATE.md
```

## To Do

+ [x] [yo](https://github.com/yeoman/yo) – yeoman/yo#492
+ [ ] [yeoman-generator-list](https://github.com/yeoman/yeoman-generator-list)
+ [ ] [generator](https://github.com/yeoman/generator)
+ [ ] [yeoman.github.io](https://github.com/yeoman/yeoman.github.io)
+ [ ] [yeoman-test](https://github.com/yeoman/yeoman-test)
+ [ ] [stringify-object](https://github.com/yeoman/stringify-object)
+ [ ] [yeoman](https://github.com/yeoman/yeoman)
+ [ ] [generator-angular](https://github.com/yeoman/generator-angular)
+ [ ] [insight](https://github.com/yeoman/insight)
+ [ ] [generator-jquery](https://github.com/yeoman/generator-jquery)
+ [ ] [environment](https://github.com/yeoman/environment)
+ [ ] [generator-webapp](https://github.com/yeoman/generator-webapp)
+ [ ] [generator-chrome-extension](https://github.com/yeoman/generator-chrome-extension)
+ [ ] [generator-generator](https://github.com/yeoman/generator-generator)
+ [ ] [generator-node](https://github.com/yeoman/generator-node)
+ [ ] [update-notifier](https://github.com/yeoman/update-notifier)
+ [ ] [generator-gruntplugin](https://github.com/yeoman/generator-gruntplugin)
+ [ ] [yeoman-app](https://github.com/yeoman/yeoman-app)
+ [ ] [yosay](https://github.com/yeoman/yosay)
+ [ ] [configstore](https://github.com/yeoman/configstore)
+ [ ] [generator-polymer](https://github.com/yeoman/generator-polymer)
+ [ ] [generator-mocha](https://github.com/yeoman/generator-mocha)
+ [ ] [yeoman-remote](https://github.com/yeoman/yeoman-remote)
+ [ ] [doctor](https://github.com/yeoman/doctor)
+ [ ] [yeoman-assert](https://github.com/yeoman/yeoman-assert)
+ [ ] [generator-karma](https://github.com/yeoman/generator-karma)
+ [ ] [generator-chromeapp](https://github.com/yeoman/generator-chromeapp)
+ [ ] [yeoman-character](https://github.com/yeoman/yeoman-character)
+ [ ] [generator-jasmine](https://github.com/yeoman/generator-jasmine)
+ [ ] [generator-bootstrap](https://github.com/yeoman/generator-bootstrap)
+ [ ] [generator-gruntfile](https://github.com/yeoman/generator-gruntfile)
+ [ ] [generator-mobile](https://github.com/yeoman/generator-mobile)
+ [ ] [generator-commonjs](https://github.com/yeoman/generator-commonjs)
+ [ ] [generator-backbone](https://github.com/yeoman/generator-backbone)

**Comment by mischah** [comment]
Thanks for the tumbsup 👍  so far. 
I’d like to make that to an actionable asap. 

So let me know if you have any feedback to the drafts. Because I’m not a native englisg speaker 😗

**Comment by SBoudrias** [comment]
Maybe open a PR, it'll be easier to comments lines.

Things I found out through lots of triaging. Most reporter don't know how to find what version of things they use.

**Comment by mischah** [comment]
Removed drafts of templates since I openend https://github.com/yeoman/yo/pull/492

**Comment by mischah** [comment]
`yo` now has an issue an PR template sind https://github.com/yeoman/yo/pull/492 landed 🎉

> Let's see how those templates do, then we can consider moving them to other repos as well.

**Comment by UlisesGascon** [comment]
@mischah do we want to promote the templates to the other repos? Are we happy with the current templates or do we want to iterate them?

**Comment by mischah** [comment]
Hej @UlisesGascon, thanks for reaching out :octocat: 

> do we want to promote the templates to the other repos? Are we happy with the current templates or do we want to iterate them?

I am pretty much inactive in the whole Open Source Contributing Game for quite a while 🙈 

But I just had a look at the most recent issues filed in [/yeoman/yo/issues](https://github.com/yeoman/yo/issues)
And I would say the provided information regarding the environment are pretty useful and it would be worth the spread the templates over the other repos.

I’m just not quite sure if it feels okay to point to the gitter rooms for general questions 🤔 … (See [/yeoman/yo/ISSUE_TEMPLATE.md](https://github.com/yeoman/yo/edit/main/.github/ISSUE_TEMPLATE.md)) because the lack of activity over there.

Your thoughts about it? 💭

**Comment by UlisesGascon** [comment]
I agree @mischah! We can spread the templates over the other repos. Regarding communications maybe we can create [dedicated channel in Nodejs Slack community](https://nodejs.org/en/get-involved/#community-discussion) to centralize and open a bit more the communications with the community 🤔

**Comment by 1DTSzumski** [comment]
Ya template makes sense not familiar. Went around all morning getting got back and wow everything I looking for was there thank you. Except for shutting off Json command important on Visual Studio say it can make a mess not shut it off of Json I named the VS. HAL kept saying yesterday only had 1.8 like 5 times little pushy I know I should not give devices human attributes no files yet just installing etc.

**Comment by JoshuaKGoldberg** [comment]
Coming back to this, I think it's definitely in scope of what #1779 is suggesting. Adding to the [Maintenance Reboot Project](https://github.com/orgs/yeoman/projects/1/views/1).

**Comment by UlisesGascon** [comment]
PR in the oven that closes this (IMO) https://github.com/yeoman/.github/pull/9 👍
