### ISSUE TITLE
Deprecate repositories of the Yeoman organisation

### ISSUE THREAD

**Issue by mischah** [yeoman/yeoman#1653]
Hej @yeoman,

shouldn’t these repos be depreacted?
+ [ ] [generator-backbone](https://github.com/yeoman/generator-backbone)
+ [x] [html-wiring](https://github.com/yeoman/html-wiring)
+ [x] [insight-dashboard](https://github.com/yeoman/insight-dashboard)

Could some with admin privileges on this repos please add a `[DEPRECATED] ` or `[UNMAINTAINED] ` prefix to the repo description?

Like https://github.com/yeoman/grunt-usemin (UNMAINTAINED) or for instance https://github.com/yeoman/bower-requirejs (DEPRECATED)

Love, Michael

**Comment by SBoudrias** [comment]
If we deprecate generators, we should redirect users to alternative.

I added the deprecated label to html-wiring and insight-dashboard

**Comment by mischah** [comment]
Thanks. Closing this. The open checkbox needs to be discussed over generator-backbone repo.
