### ISSUE TITLE
Docs for 1.0

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/yeoman#829]
From Addy: Thanks for your interest in the Yeoman docs sprint. We're hoping to spend Wednesday 30th writing lots of shiny new docs for Yeoman and hope you'll join us. Docs are a fantastic way to brush up your skills on a tool and we'll all be in the #yeoman channel on freenode if you need any help. Let us know if you would like to take part.

Sindre: Here is what we need to document for 1.0. Fill in when you find anything.
- [x] How to switch to use grunt and bower directly. Need to mention users have to do `npm install -g grunt-cli bower`.
- [ ] How to get pushState to work. Either route all traffic to index.html or set up patterns. Using grunt-contrib-connect together with middleware. (https://github.com/yeoman/yeoman/pull/670#issuecomment-12332263)
- [ ] How to use PHP with Yeoman. Lot's of requests for this. We could show of simple it is. (https://github.com/yeoman/yeoman/pull/270#issuecomment-10150543)
- [x] How to use Express with Yeoman. 
- [x] How the `install` command works, and where packages are fetched from and how the users gets them there. Ref https://github.com/yeoman/yeoman/issues/861#issuecomment-12509790
- [x] An updated guide on how to write your own generator (#761)
- [ ] How do you get Handlebars and erb templates working with Yeoman?
- [x] GitHub pages and Yeoman workflow (#850)
- [ ] How does Grunt relate to Yeoman? (#435)
- [x] Road to 1.0 and other changes since 0.9 (#775)
- [x] Documentation for Generators (e.g AngularJS)
- [ ] How to get Yeoman working with Bootstrap for LESS
- [x] Upgrade guide to 1.0. What kind of changes users has to do.
- [ ] How to use Jade, Handlebars.js, LESS, etc with Yeoman.
